FROM golang:1.16 as build

ENV GOPROXY https://goproxy.cn

WORKDIR /go/release

ADD . .

#RUN GOOS=linux CGO_ENABLED=0 go build -installsuffix cgo -o target/main cmd/main.go

FROM alpine
#FROM scratch as prod

COPY --from=build /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
#COPY --from=build /go/release/target/main /main

EXPOSE 3000

#CMD ["/main"]
CMD ["/bin/sh"]
